[package]
name = "libnetfilter_queue"
version = "0.0.2"
authors = [
    "Laurie Clark-Michalek <lclarkmichalek@gmail.com>",
    "Zach Pomerantz <zach@terminal.com>"
]

[dependencies]
lazy_static = "0.1.*"
log = "0.3.1"
env_logger = "0.3.0"
libc = "0.1"
